services:
  - type: web
    name: overengineered-todo-backend
    env: node
    buildCommand: npm install && npm install --save-dev @types/node @types/mocha @types/chai && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000 